# Promise 

## 为什么用 promise

最简单的一个解释就是解决回调地狱    

在 promise 出现之前， 要想实现异步编程，通常用的方法是用 **回调函数** 

### 同步和异步 

1. **同步**：同步就是代码按照顺序执行，上面的代码执行完，后面的代码才能执行    

2. **异步**：异步类似于中断，举个例子，网络请求时，请求是要一段时间的，   

那么，在请求这段时间内 浏览器啥都不干吗？    

显然不会，浏览器还是可以去做一些其他的事的，只是要用到请求数据的事做不了罢了。    

于是，在请求的时间内，浏览器执行其他的代码，    

当请求完成时，就要通知浏览器处理请求数据的代码可以执行了。  

这个通知过程通常是通过回调函数来实现的，数据一拿到，回调函数就会执行，处理得到的数据    

如此一来，效率就得到提升了，用户体验也变好了。

### 回调地狱

回调地狱是，一个异步嵌套着另一个异步操作。当嵌套还少的时候还能看清代码的工作原理    

但是，当嵌套多了起来，代码就已经很难阅读了，并极大可能出错。    

于是，promise 就解决了这个问题，promise 可以让代码更加优美。    

当然 promise 还有其他作用。这里不细谈    

## promise 原理


promise  是 es6 新增的引用类型 也就说他继承自 object， 是一个对象    

!['info'](./assets/promise1.jpg)

如上图，new 了一个 promise 对象 p     

p instance of Object = true    

同时，我们能看到 PromiseState = "pending"  这是 promise 的一个状态，下面来了解一下 promise 的几个状态    

### promise 的状态

1. **pending**: 待定，是 promise 的初始状态，该状态表示，异步操作正在进行中

2. **resolved**: 解决，已成功，该状态表明，异步操作已经完成，并得到异步操作结果

3. **rejected**: 拒绝，已失败，该状态表明，异步操作执行完了，但出现了错误，结果自然也就拿不到了

这三个状态只能由 pending -> resolved 或者 pending -> rejected。    

且一旦发生改变，该 promise 的状态就定型， 不会被外界所改变       

**这也就是 Promise 这个名称的由来 '承诺'**

### promise 基本用法

在继续介绍 promise 之前，先展示一个例子来使用 promise， 再来深入了解 promise    

**场景** ：在用网络请求框架，axios 或者 fetch 时，返回的通常是一个 promise 我们想处理数据只要 .then 就行了    
我们来自己用 promise 来封装一个 ajax 请求，初窥 这些网络请求框架的原理

```html
<body>
</body>
<script>
    function getData(url, method) {
        return new Promise((resolve, reject) => {
            let xhr = new XMLHttpRequest();
            xhr.open(method,url,true);
            xhr.send();
            xhr.onreadystatechange = function() {
                if(xhr.readyState !== 4) {
                    return;
                }
                if(xhr.status === 200) {
                    resolve(xhr.responseText);
                } else {
                    reject(new Error(this.statusText));
                }
            }
            
        })
    }
    getData("http://localhost:3000/say", 'GET').then((data) => {
        alert(data);
    }).catch((err) => console.log(err));

 </script>
```

服务器端代码：
```js
let express = require('express');
let app = express();

app.all('*', function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Methods","PUT,POST,GET,DELETE,OPTIONS");
    res.header("Content-Type", "application/json;charset=utf-8");
    next();
});

app.get('/say', (req,res) => {
    res.end('HELLO')
})
app.listen(3000,() => {
    console.log('serve start')
})
```
结果如下图    

!['info'](./assets/usepromise.jpg)

如上，我们可以通过给 getData 函数传递 url 和 method 来进行网络请求了。    

这里谈一点坑，    

1. 跨域请求的时候，我给的地址是 localhost:3000/say, 结果报错，因为它要求有协议，即开头要加上 http://
2. 实际上 这个封装的函数只能传 GET 方法，因为 post 和 get 处理不一样，后期可以优化    
3. 之前是这样处理的     
if(xhr.readyState === 4 && xhr.status === 200) {    
    resolve(xhr.responseText)    
    }     
    else {    
    reject(new Error())    
    }    
但是，reject 那里有点问题，导致请求一直错误，这里暂时搁置在这里。 后期补充。

好了，看过使用的例子了，我们再回到 promise 的用法上

**一**    

es6 规定，Promise 对象是一个构造函数，用来生成 Promise 实例    

下面代码创建了一个 Promise 实例    
```js
let promise = new Promise((resolve, reject) => {
    // ... some code
    if(/*异步操作成功*/) {
        resolve();
    } else {
        reject();
    }
})
```
- Promise 构造函数接受一个函数作为参数    

- 该函数的两个参数分别是 resolve，reject，它们是两个函数，由 js 引擎提供，不用自己部署，只要照写即可    

- resolve 的作用是：    
    1. 把 Promise 对象从 pending 变为 resolved，    
    2. 在异步操作成功时调用，并将异步操作的结果作为参数传出去，    

- reject 的作用是：    
    1. 把 Promise 对象从 pending 变为 rejected，    
    2. 在异步操作失败时调用，并将异步操作报出的错误作为参数传递出去

**二**    
Promise 实例创建成功后，    
可以通过 then 方法分别指定 Resolves 状态 和 Rejected 状态 的回调函数    

```js
promise.then((value) => {
    //success, 处理上该 promise 得到的结果
},(err) => {
    //failure, 处理错误信息，一般是打印
})
```
then 方法接收两个回调函数作为参数，    
1. 第一个回调函数是 Promise 对象的状态变为 resolved 时调用。    
    这个回调函数的参数就是，在 promise 对象里面 resolve(value) 所传过来的 value    
2. 第二个回调函数是 Promise 对象的转态变为 rejected 时调用。    
    这个回调函数的参数就是，在 Promise 对象里面 reject(err) 所传过来的 err

:::tip
第二个回调函数是可选的，不一定要提供。实际上，我们也很少用第二个参数，因为捕获错误一般用 .catch 方法
:::

下面是一个简单的例子    

```js
function timeout(ms) {
  return new Promise((resolve, reject) => {
    setTimeout(resolve,ms,'done');
  })
}
timeout(3000).then((val) => {
  console.log(val);
})
```

执行的结果是，3s 后，控制台输出： done， 自行分析    

可以提的一点是，setTimeOut 函数第三个参数，或者三个以后的参数，是一个参数列表，一旦定时器到期，他就会传给第一个参数，即要执行的函数的参数。上例中， done 作为参数传给了 resolve();    

至此， promise 的基本用法也就讲完了。

### Promise 使用要注意的细节    

1. 执行顺序问题     

```js
let promise = new Promise((resolve,reject) => {
  console.log('Promise');
  resolve();
});
promise.then(() => {
  console.log('resolved');
})
console.log('hi');
setTimeout(()=>{console.log('timeout')},0);

// Promise
// hi
// resolved
// timeout
```

这里来解释一下：    

- 首先， Promise 新建后，就会立执行，其中的代码是同步的，所以先打印 Promise    

- then 方法 指定的回调函数在当前脚本所有同步任务执行完毕后，才会执行，所以接着打印 hi    

- promise 的异步是优先 setTimeOut 的异步的，所以打印 then 中的回调 打印 resolved

- 最后，打印 setTimeOut 的回调 打印 timeout    

**关于 then 和 setTimeOut 的顺序 可以看此博客，说的比较好**    
['ThenAndSetTimeOut'](https://juejin.cn/post/6844903607276437517)    

2. resolve 和 reject 可以接受 promise 为参数    

看下面代码：
```js
let p1 = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error('fail')), 3000)
});

let p2 = new Promise((resolve, reject) => {
  setTimeout(() => resolve(p1), 1000)
});

p2.then(result => console.log(result))
  .catch(error => console.log(error))

// Error: fail

```
:::tip
p2 的 resolve() 方法将 p1 作为参数    
此时 p1 的状态就会传递给 p2， 也就是说， p1 的状态决定了 p2 的状态。    
如果 p1 的状态为 pending, 那么 p2 的回调函数就会等待 p1 的状态改变    
如果 p1 的状态为 resolved 或者 rejected， 那么 p2 的回调函数就会立刻执行    
:::

好了，再来看我们的代码,    

p2 要等待 3000ms, 因为 从 resolve(p1) ，开始，这个 promise 的状态就由 p1 决定了    

3000ms 后， p1 变为 rejected，p2 的回调函数立即执行    

由于 rejected, 因此 执行 catche 回调函数，打印出错误。    

3. 还有很多细节点后期补充。    

*这里用一张图总结一下，promise 的原理，也为后期叙述 promise API 做铺垫*

![原理](https://mdn.mozillademos.org/files/15911/promises.png)

## Promise 的 API    

### Promise.prototype.then()

前面也介绍了，它的作用是为 Promise 实例添加状态改变时的回调函数。    

第一个参数是 Resolved 状态的回调函数    

第二个参数是 Rejected 状态的回调函数(可选)    

这里补充的是：
**then 方法返回的是一个新的 Promise 实例 (不是原来的实例)**    

也就是说，我们可以采用链式写法，即 then 方法的后面再调用一个 then 方法。    

还是第一次用 Promise 的 ajax ， 我们链式使用它：    

```js
    getData("http://localhost:3000/1", 'GET').then((data) => {
        console.log(data);
        return  getData(data, 'GET');
    }).then((data) => {
        console.log(data)
        return getData(data, 'GET');
    }).then((data) => {
        console.log(data);
    })
```

服务器端代码修改如下：    
```js
app.get('/1', (req,res) => {
    res.end('http://localhost:3000/2')
});
app.get('/2', (req, res) => {
    res.end('http://localhost:3000/3');
});
app.get('/3', (req, res) => {
    res.end('hello3');
});
```

来解释一下，服务器端，    

- 第一个接口返回的是第二个接口地址，    
- 第二个接口返回的是第三个接口的地址    
- 第三个接口才是我们想要的数据    

你可能觉得很无脑，直接请求第三个接口数据不就得到了吗。    
确实如此，但这里是简化了一个场景：   

我们想要学生考试成绩，但是只有学生考试座位号   

数据库里有两张表，一张包含座位号和学号，另一张包含学号和成绩    
(这个在数据库是很正常的，因为为了节省存储空间，需要改进表的范式，将一个表拆解为很多表)    

为了得到成绩，你可以这样做：

1. 用座位号作为参数发送请求，得到学生的学号，    

2. 用得到的学号作为参数发送另一个请求，得到成绩    

发现了吗，这和上面服务器接口描述很相似。     
我们这里只是模拟，旨在说明这种情况会出现 ，且很常见。    

好了，来转到我们的 promise发送请求时，我们采用了链式结构，     

.then 里面将上一个 promise 的 resolve(data) 的 data 作为 url 继续发送请求   。

再回到最开始的部分，我们 promise 一个很重要的作用是解决回调地狱     

现在已经解决了 ! 不需要嵌套回调也能解决这类问题了。    


### Promise.prototype.catch()

Promise.catch() 是 .then(null, rejection) 的别名。可以说是一个语法糖    
用于指定发生错误时的回调函数    

也就是说，如果 promise 的状态变成 resolved 调 .then()    
如果 promise 的状态变成 rejected 调 .catch()    

:::tip
.catch(), 还可以捕捉到，之前 .then() 运行抛出的错误，所以我们推荐用 catch 捕获错误    
而不是用 .then() 的第二个参数    
:::

下面来简单用一下 catch, 
```js
let promise = new Promise((resolve, reject) => {
    throw new Error('catch err');
})

promise.catch((err) => {console.log(err)});
```    

下面的代码和上面是同样的的效果   

```js
let promise = new Promise((resolve, reject) => {
    reject(new Error('catch err'));
})

promise.catch((err) => {console.log(err)})
```

我们可以看出，reject 和 throw 是一样的作用    

同样的，catch 返回的也是一个 promise    

后面还可以接 .then(), 而它后面接的 .then() 里若发生错误，catch 是捕获不到的    

catch 就先谈到这里

### Promise.all()

Promise.all 方法接收多个 Promise 实例，并将包装成一个新的 Promise 实例    

```js
 let p = Promise.all([p1, p2, p3]);
 ```
上面的 p1, p2, p3 都是 Promise 对象的实例    

如果不是，就会调用  Promise.resolve() （后面介绍），将其转化为 Promise 实例    

p 的状态 由 p1, p2, p3 决定，，分两种情况    

1. 只有 p1, p2, p3 ，状态都变成 resolved ，p 的状态才变成 resolved    

    此时，p1，p2，p3 的返回值组成一个数组，传递给 p 的回调函数    

2. 只要 p1，p2，p3， 状态有一个变成 rejected， p 的状态就会变成 rejected    

    此时，第一个被 rejected 的实例的返回值会传递给 p 的回调函数    

来看下面的例子来深入了解 promise.all()    

```js
// 得到一个 promise 的数组
let promises = [2, 3, 5, 7, 11].map( id => getJSON('/post/' + id + ".json"));

Promise.all(promises),then((psots) => {
    // posts 是一个数组，里面包含了每个请求的 promise 得到的值
}).catch((err) => {
    console.log(err)
})
```
只有，所有请求都成功，每个请求都 resolve 了返回结果，才会回调 .then() 函数    

 一旦，有一个请求出错，reject 了错误，就会回调 .catch() , 处理错误    


:::tip
如果作为参数的 promise 实例，自己定义了 catch 方法，    
那么它被 rejected 时，并不会触发 Promise.all() 的 catch 方法    
因为 参数的 catch 回调执行后，又返回了一个 promise， 且该 promise 是 resolved 状态，因为处理了错误
:::

### Promsie.race()

与Promise.all() 一样， Promise.race() 也接受一个 promise 数组    

但是，正如其名，只要有一个 promise 的状态发送改变，    

那么， Promise.all()  的 promise 对象的状态就会变成第一个改变的 promise 的状态    

race 本身就是赛跑的意思，谁先转变状态就听谁的。    

用 Promise.race() 可以实现很有用的方法，如下：    

```js
const p = Promise.race([
    fetch('url'),
    new Promise((resolve, reject) => {
        setTimeOut(() => {reject(new Error('请求超时'))}, 5000)
    })
]);

p.then(res => console.log(res))
 .catch((err) => {consloe.log(err)});
```
如上，我们实现了给这个请求 限定了 5s 时间，时间到了，请求没完成就抛出错误，并在回调中打印。    

### Promise.resolve()

Promise.resolve(), 可以接收一个参数，并将它包装成 Promise 对象     

基本用法如下：

```js
let p1 =  Promise.resolve('foo');

// 等价于
let p2 = new Promise((resolve, reject) => {
    resolve('foo');
})
```

实际情况是，根据得到的不同参数，包装的过程也有所不同    

大致分为以下 4 个种类的参数：    

1. 参数是一个 Promise 实例，

这种情况不做任何修改，原封不动地返回这个实例

2. 参数是一个 thenable 对象    

这里先介绍以下 thenable：    

在 ECMAScript 暴露的异步接口中，任何对象都有一个 then() 方法    

这个方法被认为实现了 Thenable 接口，下面例子展示了实现该接口的最简单的类：    

```js
class MyThenable() {
    then() {

    }
}
```

我们的 promise 就是实现了该接口的类， 所以我们才能调用 .then() 方法    

对于实现了该接口的对象作为参数， Promise.resolve() 会将它转为 Promise 对象    

并且立即执行其中的 then() 方法。

用法如下：    
```js
let thenable = {
    then: (resolve, reject) => {
        resolve(42);
    }
};

let p = Promise.resolve(thenable);

p.then((value) => {
    console.log(value);
})
// 42
```
3. 参数是不具有 then 方法的对象，或根本不是对象    

这种情况，Promise.resolve() 返回一个新的 Promise 对象，状态为 Resolved    

并 resolve() 这个参数，也就是说，之后可以用 .then() 方法获取这个参数来使用    

例子如下：    
```js
let str = 'hello';

let p = Promise.resolve(str);

p.then((val) => {
    console.log(val);
})   
```

4. 不带任何参数    

Promise.resolve() 允许不带任何参数，直接返回一个 resolved 的 Promise    

所以，如果希望得到一个 Promise 对象，比较方便的是直接调用该方法。    

:::tip
立即 resolve 的对象是在本轮时间循环结束时，而不是下一轮事件循环开始时，    
通俗的说，就是，本轮同步代码结尾就会调用其回调了(then, catch ,等)    
而 setTimeOut 是把任务放到消息队列中去的，是第二轮循环开始执行
:::

看下面代码：
```js
setTimeOut(() => {
    console.log(3);
});

let p = Promise.resolve().then(() => {
    console.log(2);
});

console.log(1);

// 1
// 2
// 3
```
### Promise.reject() 

用法和 Promise.reject() 相似，

用法如下：

```js
let err = '出错了';
let p = Promise.reject(err);
//  等价于
let p = new Promise((resolve, reject) => {
    reject(new Error('出错了'))
})

p.catch((err) => {
    console.log(err)
});
```

:::tip
Promise.reject() 获得的参数会原封不动的作为 reject 的理由变为后续回调的参数    
这点与 Promise.resolve() 不一样
:::

## 总结
Promise 的内容就先谈到这里了，后续碰到了还会继续补充    

参考： 阮一峰的es6入门











